### ISSUE TITLE
cli installation error (MacOS)

### ISSUE THREAD

**Issue by nehamoopen** [hypergraph-xyz/cli#57]
I'm running MacOS Catalina (version 10.15.1), and I'm unable to install the cli version of Hypergraph. I've included the error message below, note during previous trials I also had to install `libtool`, `autoconf`, and `automake` because the message mentioned they were required but not available on my system.

```bash
npm WARN deprecated core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/local/bin/hypergraph -> /usr/local/lib/node_modules/@hypergraph-xyz/cli/bin/hypergraph.js

> fd-lock@1.0.2 install /usr/local/lib/node_modules/@hypergraph-xyz/cli/node_modules/fd-lock
> node-gyp-build
> sodium-native@2.4.6 install /usr/local/lib/node_modules/@hypergraph-xyz/cli/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autom4te: need GNU m4 1.4 or later: /usr/bin/m4
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
./configure: line 5: ./configure: No such file or directory
/usr/local/lib/node_modules/@hypergraph-xyz/cli/node_modules/sodium-native/preinstall.js:119
    if (err) throw err
             ^

Error: ./configure exited with 127
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@hypergraph-xyz/cli/node_modules/sodium-native/preinstall.js:149:25)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium-native@2.4.6 install: `node-gyp-build "node preinstall.js" "node postinstall.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium-native@2.4.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Name/.npm/_logs/2019-12-03T11_56_05_681Z-debug.log
```

**Comment by juliangruber** [comment]
Thank you for reporting this. We definitely don't want user to have to set up build toolchains on their machines. I'm investigating this :)

**Comment by juliangruber** [comment]
Which node version are you using? `node -v`

**Comment by nehamoopen** [comment]
It's v13.2.0 :)
I installed it through Homebrew.

**Comment by juliangruber** [comment]
Ok I can reproduce. This node version is newer than what I was testing with. I'll open issues in the respective repos to provide prebuilt binaries, so we don't have to compile when installing.

**Comment by juliangruber** [comment]
If you want a quick fix, downgrade to node 12

**Comment by juliangruber** [comment]
Blocked by https://github.com/sodium-friends/sodium-native/pull/114

**Comment by nehamoopen** [comment]
It's working now! 👍 

Just as an FYI for someone who might care, I downgraded to node 12 and this showed up as part of the message:

```
==> Caveats
node@12 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.
If you need to have node@12 first in your PATH run:
  echo 'export PATH="/usr/local/opt/node@12/bin:$PATH"' >> ~/.bash_profile
For compilers to find node@12 you may need to set:
  export LDFLAGS="-L/usr/local/opt/node@12/lib"
  export CPPFLAGS="-I/usr/local/opt/node@12/include" 
```
I didn't do anything with the above, and tried the installation. I got:
```env: node: No such file or directory```

Finally, I ran the following:
```echo 'export PATH="/usr/local/opt/node@12/bin:$PATH"' >>source ~/.bash_profile```

And the installation went fine after that :)

**Comment by juliangruber** [comment]
Thank you for sharing your experience!

**Comment by juliangruber** [comment]
Still waiting on https://github.com/sodium-friends/sodium-native/pull/114
